In [6]:
from simhash import Simhash
import cv2
import numpy as np
from PIL import Image
import requests
from io import BytesIO
import os

def simhash_similarity(text1,text2):
    
    a_simhash = Simhash(text1)
    b_simhash = Simhash(text2)
    
    max_hashbit = max(len(bin(a_simhash.value)),len(bin(b_simhash.value)))

    distince = a_simhash.distance(b_simhash)

    similar = round(distince/max_hashbit,2)

def getImageByUrl(url):
    # 根据图片url 获取图片对象
    html = requests.get(url, verify=False)
    image = Image.open(BytesIO(html.content))
    return image

        
if __name__ == "__main__":
    
    p1="https://ww3.sinaimg.cn/bmiddle/007INInDly1g336j2zziwj30su0g848w.jpg"
    p2="https://ww2.sinaimg.cn/bmiddle/007INInDly1g336j10d32j30vd0hnam6.jpg"

    if p1.startswith("http"):
     # 根据链接下载图片，并转换为opencv格式
        img1 = getImageByUrl(p1)
        img1 = cv2.cvtColor(np.asarray(img1), cv2.COLOR_RGB2BGR)

        img2 = getImageByUrl(p2)
        img2 = cv2.cvtColor(np.asarray(img2), cv2.COLOR_RGB2BGR)
    else:
    # 通过imread方法直接读取物理路径
        img1 = cv2.imread(para1)
        img2 = cv2.imread(para2)

        similars = simhash_similarity(img1,img2)
        
        similars

C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww3.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww2.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


In [22]:
from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt

def getImageByUrl(url):
    # 根据图片url 获取图片对象
    html = requests.get(url, verify=False)
    image = Image.open(BytesIO(html.content))
    return image

def runAllImageSimilaryFun(para1, para2):
    # 均值、差值、感知哈希算法三种算法值越小，则越相似,相同图片值为0
    # 三直方图算法和单通道的直方图 0-1之间，值越大，越相似。 相同图片为1
 
    # t1,t2   14;19;10;  0.70;0.75
    # t1,t3   39 33 18   0.58 0.49
    # s1,s2  7 23 11     0.83 0.86  挺相似的图片
    # c1,c2  11 29 17    0.30 0.31
 
    if para1.startswith("http"):
         # 根据链接下载图片，并转换为opencv格式
        img1 = getImageByUrl(para1)
        img1 = img1.resize((500,500))
        gray1 = cv2.cvtColor(np.asarray(img1), cv2.COLOR_RGB2BGR)
 
        img2 = getImageByUrl(para2)
        img2 = img2.resize((500,500))
        gray2 = cv2.cvtColor(np.asarray(img2), cv2.COLOR_RGB2BGR)
    else:
        # 通过imread方法直接读取物理路径
        img1 = cv2.imread(para1)
        img1 = cv2.resize(img1,(500,500))
        gray1 = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
        
        img2 = cv2.imread(para2)
        img2 = cv2.resize(img2,(500,500))
        gray2 = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
        
    sift = cv2.xfeatures2d.SIFT_create()
    kp = sift.detect(gray,None)  #搜索关键点
#     print(gray1+gray2)

In [23]:
if __name__ == "__main__":
    p1="https://ww3.sinaimg.cn/bmiddle/007INInDly1g336j2zziwj30su0g848w.jpg"
    p2="https://ww2.sinaimg.cn/bmiddle/007INInDly1g336j10d32j30vd0hnam6.jpg"
    n = runAllImageSimilaryFun(p1,p2)

C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww3.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww2.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


[[[106 105 108]
  [107 106 109]
  [108 107 110]
  ...
  [161 158 161]
  [161 158 161]
  [159 156 159]]

 [[106 105 108]
  [107 106 109]
  [108 107 110]
  ...
  [161 158 161]
  [161 158 161]
  [159 156 159]]

 [[106 105 108]
  [107 106 109]
  [108 107 110]
  ...
  [162 159 162]
  [161 158 161]
  [160 157 160]]

 ...

 [[114 129 169]
  [112 129 169]
  [116 132 173]
  ...
  [ 50  43  53]
  [ 53  48  56]
  [ 52  47  55]]

 [[108 123 162]
  [106 120 162]
  [107 123 165]
  ...
  [ 55  49  56]
  [ 52  48  55]
  [ 42  37  44]]

 [[105 121 159]
  [104 117 159]
  [104 119 162]
  ...
  [ 57  51  57]
  [ 52  48  54]
  [ 36  32  38]]]


In [16]:
from PIL import Image
html = requests.get("https://ww3.sinaimg.cn/bmiddle/007INInDly1g336j2zziwj30su0g848w.jpg", verify=False)
image = Image.open(BytesIO(html.content))
img1 = image.resize(image,(500,500))

C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww3.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


In [47]:
from PIL import Image
import cv2
import numpy as np
import matplotlib.pyplot as plt
#计算特征点
img1 = getImageByUrl("https://ww3.sinaimg.cn/bmiddle/007INInDly1g336j2zziwj30su0g848w.jpg")
img1 = 255 * np.array(img1).astype('uint8')
img1 = cv2.resize(img1,(500,500))
gray1 = cv2.cvtColor(np.asarray(img1), cv2.COLOR_RGB2BGR)
# cv2.imshow("img1",img1)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

sift = cv2.SIFT_create()
kp = sift.detect(gray1,None)  #搜索关键点
img_sift = cv2.drawKeypoints(img1,kp,img1) #绘制关键点
# cv2.imshow("img_sift",img_sift)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

kp,des = sift.compute(gray1,kp)  #计算关键点 得到关键点参数
print(len(kp))
print (des.shape)
print (des[0])

C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww3.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


345
(345, 128)
[  0.   2.   2.   0.   0.   0.   0.   0.   9.  47.  24.   2.   6.   0.
   0.   0.   4.   6.   4.  51.  19.   4.   0.   0.   0.   0.  76. 117.
  12.   2.   1.   0.   9.  11.   2.   0.   0.   0.   0.   1. 138. 138.
  16.   8.  10.   1.   0.   6.  52.  15.  13. 138. 123.  11.   0.   1.
   0.   0.  55. 138.  35.   9.  12.   7.  15.   1.   0.   0.   0.   0.
   9.  21. 138.  10.   0.   2.  13.   6.  23. 138.  47.   1.   1.  27.
 138. 138.  32.  14.   0.   0.   3.  17.  30.  69. 138.  83.   0.   0.
   0.   0.   0.   0.  15.  10.  14.   0.   1.   0.   1.   3.  41.  84.
   3.   0.   0.   1.   7.  58.  32.   7.   0.   0.   0.   2.   4.  27.
  91.  21.]


In [55]:
#蛮力匹配
img1 = getImageByUrl("https://ww3.sinaimg.cn/bmiddle/007INInDly1g336j2zziwj30su0g848w.jpg")
img1 = 255 * np.array(img1).astype('uint8')
img1 = cv2.resize(img1,(500,500))

img2 = getImageByUrl("https://ww2.sinaimg.cn/bmiddle/007INInDly1g336j10d32j30vd0hnam6.jpg")
img2 = 255 * np.array(img2).astype('uint8')
img2 = cv2.resize(img2,(500,500))

# cs1 = cv2.imread("cs1.jpg")
# cs2 = cv2.imread("cs2.jpg")
# img1 = cv2.resize(cs1,(500,500))
# img2 = cv2.resize(cs2,(500,500))

kp1 = sift.detect(img1,None)
kp2 = sift.detect(img2,None)
kp1,des1 = sift.compute(img1,kp1,img1)
kp2,des2 = sift.compute(img2,kp2,img2)

bf = cv2.BFMatcher(crossCheck=True) #计算本图特诊算子与对比图特征算子的距离并返回最小值
matches = bf.match(des1,des2)
matches = sorted(matches,key=lambda x:x.distance)
img3 = cv2.drawMatches(img1,kp1,img2,kp2,matches[:50],None,flags=2)
cv2.imshow("img3",img3)
cv2.waitKey(0)
cv2.destroyAllWindows()
#一对多的匹配
bf = cv2.BFMatcher()
matches2 = bf.knnMatch(des1,des2,k=2)
good = []
for m,n in matches2:
    if m.distance<n.distance*0.75:
        good.append([m])
img4 = cv2.drawMatches(img1,kp1,img2,kp2,good,None,flags=2)
cv2.imshow("img4",img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww3.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\User\anaconda3\lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'ww2.sinaimg.cn'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  warnings.warn(


TypeError: Expected cv::DMatch for argument 'matches1to2'

In [57]:
# FLANN
FLANN_INDEX_KDTREE = 1
index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
search_params = dict(checks=50)


flann = cv2.FlannBasedMatcher(index_params,search_params)

matches = flann.knnMatch(des1,des2,k=2)

matchesMask = [[0,0] for i in range(len(matches))]

for i,(m,n) in enumerate(matches):

#如果第一个邻近距离比第二个邻近距离的0.7倍小，则保留
    if m.distance < 0.7*n.distance:
        matchesMask[i]=[1,0]


draw_params = dict(matchColor = (0,255,0),
                   singlePointColor = (255,0,0),
                   matchesMask = matchesMask,
                   flags = 0)


img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,matches,None,**draw_params)
cv2.imshow("img5",img5)
cv2.waitKey(0)
cv2.destroyAllWindows()
# plt.imshow(img3,),plt.show()